---
kind: ReplicaSet                                    
apiVersion: apps/v1                            
metadata:
  name: myrs
spec:
  replicas: 4 
  selector:                  
    matchExpressions:                             # these must match the labels
      - {key: myname, operator: In, values: [Arvind, Arind, Agaur]}
      - {key: env, operator: NotIn, values: [production]}
  template:      
    metadata:
      name: testpod7
      labels:              
        myname: Arvind
    spec:
     containers:
       - name: c06
         image: ubuntu
         command: ["/bin/bash", "-c", "while true; do echo radhey radhey; sleep 5 ; done"]