---
kind: Pod
apiVersion: v1
metadata:
  name: testpod
spec:
  containers:
    - name: c10
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo Jai Shree Radhey; sleep 5 ; done"]
    - name: c11
      image: httpd
      ports:
       - containerPort: 80